config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  get 'home/index'

  root 'home#index'

  get 'home/login' => 'home#login'
  get 'home/signup' => 'home#signup'
  get 'home/signupsubmit' => 'home#signupsubmit'
  get 'home/loginsubmit' => 'home#loginsubmit'
  get 'home/logout' => 'home#logout'
  get 'dashboard/index' => 'dashboard#index'
  get 'quiz/create_quiz' => 'quiz#create_quiz'
  get 'quiz/upload_quiz' => 'quiz#upload_quiz'
  post 'quiz/upload' => 'quiz#upload'
  get 'quiz/create' => 'quiz#create'
  get 'problem/add_problem' => 'problem#add_problem'
  get 'problem/add_prob' => 'problem#add_prob'
  get 'quiz/my_quiz' => 'quiz#my_quiz'
  get 'quiz/score' => 'quiz#score'
  get 'quiz/init_quiz' => 'quiz#init_quiz', as: :start_quiz

end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
	belongs_to :user
	belongs_to :quiz
	belongs_to :problem
end

app/models/problem.rb
class Problem < ActiveRecord::Base
	belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
	belongs_to :user
	has_many :problems
end

app/models/quiz_attended.rb
class QuizAttended < ActiveRecord::Base
	belongs_to :user
	belongs_to :quiz
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    puts "%"*50
    puts session[:user_id]
    puts "%"*50
  	if params[:type].nil?
  		params[:type] = "all"
  	end
  	@selected = params[:type]
  	if params[:type].to_s == "all"
  		@all_quiz = Quiz.find_by_sql(["select * from quizzes where user_id != ? ", session[:user_id]])
  	else	  	
		@all_quiz = Quiz.find_by_sql(["select * from quizzes where user_id != ? and quiz_type = ? ", session[:user_id], params[:type]])  
	end		
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def login

  end
  def signup
  	
  end
  def signupsubmit
  	user_obj = User.find_by_sql(["select * from users where username = ? or email = ? ",params[:username],params[:email]])
  	puts "&"*50
  	puts user_obj.inspect
  	puts "&"*50
  	if user_obj.empty?
  		new_obj = User.new
  		new_obj.firstname = params[:firstname]
  		new_obj.lastname = params[:lastname]
  		new_obj.username = params[:username]
  		new_obj.email = params[:email]
  		new_obj.date_ob = params[:date_ob]
  		new_obj.password = params[:password]
  		new_obj.save
  		redirect_to action: 'login'
  	else
  		redirect_to action: 'signup'
  	end
  
  		
  end
  def loginsubmit
    user_obj= User.find_by_sql(["select * from users where username = ? and password = ? ",params[:username],params[:password]])[0]
    puts user_obj.inspect
    if user_obj.nil? 
      redirect_to action: 'login'
    else
      puts user_obj.inspect
      session[:email] = user_obj.email
      session[:user_id] = user_obj.id
      redirect_to :controller=>'dashboard', :action => 'index'
 
    end
  end

  def logout
    session[:email] = nil
    session[:user_id] = nil
    redirect_to action: 'index'
  end

end

app/controllers/problem_controller.rb
class ProblemController < ApplicationController
	def add_problem
	end
	def add_prob
		prob_obj = Problem.new
		prob_obj.prob_stat = params[:problem]
		prob_obj.option1 = params[:option1]
		prob_obj.option2 = params[:option2]
		prob_obj.option3 = params[:option3]
		prob_obj.option4 = params[:option4]
		prob_obj.prob_ans = params[:answer]
		prob_obj.quiz_id = session[:quiz_id]
		prob_obj.save!
		if params[:decider].to_i == 0
			redirect_to :action => 'add_problem'
		else
			redirect_to :controller => 'dashboard',:action => 'index'
		end
	end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
def create_quiz
end 
def create
puts "&"*50
puts params[:quiz_name]
puts "&"*50
create_obj= Quiz.find_by_sql(["select * from quizzes where quiz_name = ? ",params[:quiz_name]])
if create_obj.empty?
new_obj = Quiz.new
new_obj.quiz_name = params[:quiz_name]
new_obj.quiz_type = params[:quiz_type]
new_obj.user_id = session[:user_id].to_i
new_obj.save!
session[:quiz_id] = new_obj.id
user_obj=User.find(session[:user_id].to_i)
if user_obj.quiz_organised.nil?
user_obj.update_attributes(:quiz_organised => 1)
else
user_obj.update_attributes(:quiz_organised => user_obj.quiz_organised+1)
end
redirect_to :controller=>'problem', :action => 'add_problem'
else
redirect_to action: 'create_quiz'
end
end
def my_quiz
@my_quiz=Quiz.find_by_sql(["select * from quizzes where user_id = ? ",session[:user_id]])
end
def init_quiz
total_count = Problem.find_by_sql(["select * from problems where quiz_id = ? ",params[:quiz_id]]).count
if total_count <= params[:problem_id].to_i
redirect_to action: 'score'
end
@problem=Problem.find_by_sql(["select * from problems where quiz_id = ? ",params[:quiz_id]])[params[:problem_id].to_i]
@quiz_id=params[:quiz_id]
@prob_count=params[:problem_id].to_i+1
if params[:problem_id] != 0
if !params[:option].nil?
prob_info = Attempt.new
temp = Problem.find_by_sql(["select * from problems where quiz_id = ?",params[:quiz_id]])[params[:problem_id].to_i - 1]
prob_info.problem_id = temp.id
prob_info.user_id = session[:user_id]
prob_info.quiz_id = params[:quiz_id]
prob_info.option = params[:option]
prob_info.save!
quiz_info = QuizAttended.find_by_sql(["select *from quiz_attendeds where user_id = ? and quiz_id = ?",session[:user_id],params[:quiz_id]])[0]
#to check answer is correct or not.
prev_correct = Problem.find_by_sql(["select * from problems where quiz_id = ?",params[:quiz_id]])[params[:problem_id].to_i-1]
prev_correct_ans = prev_correct.prob_ans.to_i
score = 0
if prev_correct_ans == params[:option].to_i
score = 1
end
if quiz_info.nil?
# to create entry
quiz_attend_obj = QuizAttended.new
quiz_attend_obj.user_id = session[:user_id]
quiz_attend_obj.score = score
puts "*"*50
puts score
puts "*"*50
quiz_attend_obj.quiz_id = params[:quiz_id]
quiz_attend_obj.save!
else
#update entry
quiz_obj = Quiz.find_by_sql(["select *from quiz_attendeds where quiz_id = ? and user_id = ?",params[:quiz_id],session[:user_id]])[0]
quiz_obj.update_attributes(:score => quiz_obj.score.to_i + score)
end
end
end
end
def score
@quiz_score = QuizAttended.find_by_sql(["select score from quiz_attendeds where quiz_id = ? and user_id = ?",params[:quiz_id], session[:user_id]])[0]
puts "%"*50
puts @quiz_score
puts "%"*50
end

def upload
  uploaded_file = params[:file]
  file_content = uploaded_file.read
  file_content = file_content.to_s.split("\n")
  create_obj= Quiz.find_by_sql(["select * from quizzes where quiz_name = ? ",file_content[0].to_s])
  if create_obj.empty?
    new_obj = Quiz.new
    new_obj.quiz_name = file_content[0].to_s #quiz name
    new_obj.quiz_type = file_content[1].to_s #quiz_type
    new_obj.user_id = session[:user_id].to_i
    new_obj.save!
    session[:quiz_id] = new_obj.id
    user_obj=User.find(session[:user_id].to_i)
    if user_obj.quiz_organised.nil?
      user_obj.update_attributes(:quiz_organised => 1)
    else
      user_obj.update_attributes(:quiz_organised => user_obj.quiz_organised+1)
    end
    no_of_questions = file_content[2].to_i
    i = 0
    while i < no_of_questions
      prob_obj = Problem.new
      prob_obj.prob_stat = file_content[3+i*6+0]
      prob_obj.option1 = file_content[3+i*6+1]
      prob_obj.option2 = file_content[3+i*6+2]
      prob_obj.option3 = file_content[3+i*6+3]
      prob_obj.option4 = file_content[3+i*6+4]
      prob_obj.prob_ans = file_content[3+i*6+5]
      prob_obj.quiz_id = session[:quiz_id]
      prob_obj.save!
      i = i+1
    end
  else
    redirect_to action: 'create_quiz'
  end
  redirect_to :controller=>'dashboard', :action => 'index'
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/dashboard/index.html.erb
<nav class="navbar navbar-default navbar-static-top">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">
				Quizapp
			</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">			
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown ">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
						Account
						<span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="/home/index">Logout</a></li>
						</ul>
					</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
	<div class="container-fluid main-container">
		<div class="col-md-2 sidebar">
			<ul class="nav nav-pills nav-stacked">
				<li class="active"><a href="#">Home</a></li>
				<li><a href="/quiz/create_quiz">Create Quiz</a></li>
				<li><a href="/quiz/upload_quiz">Upload Quiz</a></li>
				<li><a href="/quiz/my_quiz">My Quizzes</a></li>
				<select id="sel">
  <option id="all" value="all">All</option>
  <option id="general" value="general">General</option>
  <option id="movies" value="movies">Movies</option>
  <option id="entertainment" value="entertainment">Entertainment</option>
  <option id="literature" value="literature">Literature</option>
  <option id="sports" value="sports">Sports</option>
  <option id="arts" value="arts">Arts</option>
</select> 
<table>
<% @all_quiz.each do |quiz| %>
	<tr>
	<td><%=quiz.quiz_name%></td>
	<td><%=quiz.quiz_type%></td>
	<td><%=link_to "Participate", start_quiz_path(:quiz_id => quiz.id, :problem_id => 0)%></td>
</br>

	</tr>
<%end%>
</table>

<script>
$("#sel").on('change',function(){
	if(window.location.href.indexOf('?') == -1)
	{
		window.location.href += "?type="+$('#sel').val();
	}
	else
	{
		window.location.href = window.location.href.substr(0,window.location.href.indexOf('=')+1)+$('#sel').val();
	}
});
</script>

<script>
$('document').ready(function(){
	$("#sel").val("<%=@selected%>");
});
</script>
				
			</ul>
		</div>
		<div class="col-md-10 content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Dashboard
                </div>
                <div class="panel-body">
                  Hello member! Welcome to QuizApp.Enjoy.
                </div>
            </div>
		</div>
	</div>

app/views/dashboard/index1.html.erb
<h1>Dashboard</h1>

<a href="/quiz/create_quiz"><button type="Create">Create a quiz</button></a>
<a href="/quiz/my_quiz"><button type="my_quiz">My quiz</button></a>
<a href="/home/index"><button type="logout">logout</button></a>
</br>
<select id="sel">
  <option id="all" value="all">All</option>
  <option id="general" value="general">General</option>
  <option id="movies" value="movies">Movies</option>
  <option id="entertainment" value="entertainment">Entertainment</option>
  <option id="literature" value="literature">Literature</option>
  <option id="sports" value="sports">Sports</option>
  <option id="arts" value="arts">Arts</option>
</select> 
<table>
<% @all_quiz.each do |quiz| %>
	<tr>
	<td><%=quiz.quiz_name%></td>
	<td><%=quiz.quiz_type%></td>
	<td><%=link_to "Participate", start_quiz_path(:quiz_id => quiz.id, :problem_id => 0)%></td>
</br>

	</tr>
<%end%>
</table>

<script>
$("#sel").on('change',function(){
	if(window.location.href.indexOf('?') == -1)
	{
		window.location.href += "?type="+$('#sel').val();
	}
	else
	{
		window.location.href = window.location.href.substr(0,window.location.href.indexOf('=')+1)+$('#sel').val();
	}
});
</script>

<script>
$('document').ready(function(){
	$("#sel").val("<%=@selected%>");
});
</script>

app/views/home/index.html.erb
<div class="container">
<h1>Welcome to the quizzeraaa!</h1>
<div class="row">
<div class="col-md-3"></div>
<div class="col-md-3"><a href="/home/signup"><button>Sign Up</button></a></div>
<div class="col-md-3"><a href="/home/login"><button>Sign In</button></a></div>
<div class="col-md-3"></div>
</div>
</div>

app/views/home/login.html.erb
<div class="container">
        <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
        	<div class="panel panel-default">
        		<div class="panel-heading">
			    		<h3 class="panel-title">Sign In for QuizApp</h3>
			 			</div>
			 			<div class="panel-body">
			    		<form role="form" action="/home/loginsubmit" method="GET">
			    			<div class="row">
			    				
					    		<div class="col-xs-6 col-sm-6 col-md-6">
					    			<div class="form-group">
					    				<input type="text" name="username" id="username" class="form-control input-sm" placeholder="Username">
					    			</div>
					    		</div>

					    		<div class="col-xs-6 col-sm-6 col-md-6">
					    			<div class="form-group">
					    				<input type="password" name="password" id="password" class="form-control input-sm" placeholder="Password">
					    			</div>
					    		</div>
			    			</div>

			    			<input type="submit" value="Submit" class="btn btn-info btn-block">
			    		
			    		</form>
			    	</div>
	    		</div>
    		</div>
    	</div>
    </div>

app/views/home/signup.html.erb
<div class="container">
        <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
        	<div class="panel panel-default">
        		<div class="panel-heading">
			    		<h3 class="panel-title">Please sign up for QuizApp <small>It's free!</small></h3>
			 			</div>
			 			<div class="panel-body">
			    		<form role="form" action="/home/signupsubmit" method="GET">
			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			                <input type="text" name="first_name" id="first_name" class="form-control input-sm" placeholder="First Name">
			    					</div>
			    				</div>
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="text" name="last_name" id="last_name" class="form-control input-sm" placeholder="Last Name">
			    					</div>
			    				</div>
			    			</div>

			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
					    			<div class="form-group">
					    				<input type="email" name="email" id="email" class="form-control input-sm" placeholder="Email Address">
					    			</div>
					    		</div>
					    		<div class="col-xs-6 col-sm-6 col-md-6">
					    			<div class="form-group">
					    				<input type="text" name="username" id="username" class="form-control input-sm" placeholder="Username">
					    			</div>
					    		</div>
			    			</div>

			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="password" name="password" id="password" class="form-control input-sm" placeholder="Password">
			    					</div>
			    				</div>
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="date" name="date_ob" id="date" class="form-control input-sm" placeholder="Date of Birth">
			    					</div>
			    				</div>
			    			</div>
			    			
			    			<input type="submit" value="Submit" class="btn btn-info btn-block">
			    		
			    		</form>
			    	</div>
	    		</div>
    		</div>
    	</div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quizapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/problem/add_problem.html.erb
<h1>Welcome</h1>
<form action="add_prob" method="GET">
Problem
</br>
<textarea name="problem" rows="5" cols="50"></textarea>
</br>
option1<input type="text" name="option1"><br>
option2<input type="text" name="option2"><br>
option3<input type="text" name="option3"><br>
option4<input type="text" name="option4"><br>
Answer<input type="text" name="answer"><br>
<input style="visibility:hidden;" id="decider" type="text" name="decider" value="0"></input>
<br>
<button id="add" type="submit">Add a new problem</button>
<button id="end" type="submit">End</button>
</form> 

<script>
$('#add').on('click',function(){
	  $('#decider').val("0");
});
$('#end').on('click',function(){
	  $('#decider').val("1");
});
</script>

app/views/quiz/create_quiz.html.erb
<h1>Create quiz</h1>
 <form action="/quiz/create" method="GET">
Quiz name:<br>
<input type="text" name="quiz_name">
<br>
Quiz type:<br>
<input type="text" name="quiz_type">
</br>

<button type="submit">Submit</button>
</form> 

app/views/quiz/init_quiz.html.erb
<p>question <%=@prob_count%>. <%=@problem.prob_stat %></p>
<form action='init_quiz' method="GET" >
<input type="radio" name="option" value="1"><%=@problem.option1%><br>
<input type="radio" name="option" value="2"><%=@problem.option2%><br>
<input type="radio" name="option" value="3"><%=@problem.option3%><br>
<input type="radio" name="option" value="4"><%=@problem.option4%><br>
<input id="b1" type="submit" name="next" value="Next">
<input id="b2" type="submit" name="end" value="End quiz">
<input style="visibility:hidden;" id="decider" type="text" name="decider" value="0"></input>
<input style="visibility:hidden;" id="quiz_id" type="text" name="quiz_id" value="<%=@quiz_id%>"></input>
<input style="visibility:hidden;" id="problem_id" type="text" name="problem_id" value="<%=@prob_count%>"></input>
</form>

<script>
$('#b1').on('click',function(){
	  $('#decider').val("0");
});
$('#b2').on('click',function(){
	  $('#decider').val("1");
});
</script

app/views/quiz/my_quiz.html.erb
<h1>Quizzes created by me</h1>
<table>
<tr>
<th>Quiz Name</th>
<th>Quiz Type</th>
</tr>
<% @my_quiz.each do |quiz| %>
<tr>
<td><%=quiz.quiz_name%></td>
<td><%=quiz.quiz_type%></td
</tr>
<%end%>
</table>

app/views/quiz/score.html.erb
<h1> Your score is <%=@quiz_score %> </h1>

app/views/quiz/upload_quiz.html.erb
<%= form_tag '/quiz/upload', :multipart => true do %>
   <label for="file">Upload text File</label> <%= file_field_tag "file" %>
   <%= submit_tag %>
<% end %>